// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserStory4Tours;

namespace UserStory4Tours.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserStory4Tours.models.Tours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CostVac")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("MigrationVerification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberNight")
                        .HasColumnType("int");

                    b.Property<int>("NumberVac")
                        .HasColumnType("int");

                    b.Property<decimal>("Surcharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Wi_Fi")
                        .HasColumnType("bit");

                    b.Property<int>("direction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ToursDB");
                });
#pragma warning restore 612, 618
        }
    }
}
